"""Vector CANape 的 Python COM 控制接口。"""

from .ai_tools import (
    AIActionPlan,
    AIToolRegistry,
    AIToolSpec,
    ApprovalStore,
    CANapeAIToolkit,
    EngineeringCommandPlanner,
    ToolRisk,
)
from .analysis import Finding, SignalAnalyzer
from .assets import AssetManager, AssetRecord, PreflightResult
from .calibration import (
    CalibrationChange,
    CalibrationConstraintSet,
    CalibrationDataset,
    CalibrationDatasetConstraint,
    CalibrationExperiment,
    CalibrationIdentity,
    CalibrationKind,
    CalibrationMath,
    CalibrationOptimizer,
    CalibrationParameter,
    CalibrationPlan,
    CalibrationRepository,
    CalibrationSession,
    ParameterConstraint,
    RelationConstraint,
    SweepParameter,
)
from .calibration_design import (
    CalibrationExperimentReport,
    CalibrationObservation,
    ExperimentQualityPolicy,
    MapNeighborhoodConstraint,
    MetricAcceptanceRule,
    OutlierRule,
    PhysicalModelConstraint,
    SafeBayesianCalibrationOptimizer,
    SteadyStateRule,
)
from .calibration_formats import (
    A2LAxisDescriptor,
    A2LCatalog,
    A2LCompuMethod,
    A2LObject,
    A2LRecordLayout,
    CalibrationDatasetIO,
)
from .calibration_operations import (
    CalibrationCandidate,
    CalibrationChangeItem,
    CalibrationChangeSet,
    CalibrationExperimentRunner,
    CalibrationExperimentStore,
    CalibrationMemoryLayer,
    CalibrationMemoryLedger,
    CalibrationObjective,
    CalibrationReview,
    ChangeSetStatus,
    ECUCalibrationTask,
    ExperimentCaseRecord,
    ExperimentCaseStatus,
    ExperimentEvidence,
    MultiECUCalibrationCoordinator,
    ParetoCalibrationAnalysis,
    ReviewDecision,
)
from .calibration_targets import (
    CalibrationPersistenceCoordinator,
    CalibrationPersistenceJob,
    CalibrationTargetAdapter,
    CANapeCalibrationTarget,
    InMemoryCalibrationTarget,
    PersistenceStatus,
    StagedECUPersistenceTask,
    StagedMultiECUPersistenceCoordinator,
)
from .canape import CANape
from .capabilities import Capability, CapabilityRegistry
from .errors import (
    AssetValidationError,
    CANapeCOMError,
    CANapeError,
    CANapeNotConnectedError,
    CANapeObjectNotFoundError,
    CANapeProjectError,
    OptionalDependencyError,
    SafetyViolationError,
    WorkflowError,
)
from .models import (
    CalibrationObjectInfo,
    CANapeVersion,
    DeviceInfo,
    DiagnosticResponse,
    FlashStateInfo,
    RecorderInfo,
    TaskInfo,
)
from .offline import OfflineData, SignalDefinition, SignalDictionary
from .platform import EngineeringPlatform
from .plugins import BasicDomainAdapter, PluginRegistry, built_in_domains
from .reporting import AuditEntry, AuditTrail, Reporter
from .safety import (
    EnvironmentSecretProvider,
    PermissionLevel,
    SafeCANape,
    SafetyPolicy,
    ValueRule,
)
from .workflow import StepResult, WorkflowEngine, WorkflowResult

__all__ = [
    "CANape",
    "ToolRisk",
    "AIToolSpec",
    "AIActionPlan",
    "ApprovalStore",
    "AIToolRegistry",
    "EngineeringCommandPlanner",
    "CANapeAIToolkit",
    "CalibrationKind",
    "CalibrationParameter",
    "CalibrationDataset",
    "CalibrationDatasetIO",
    "CalibrationRepository",
    "CalibrationIdentity",
    "ParameterConstraint",
    "RelationConstraint",
    "CalibrationConstraintSet",
    "CalibrationDatasetConstraint",
    "MapNeighborhoodConstraint",
    "PhysicalModelConstraint",
    "SteadyStateRule",
    "MetricAcceptanceRule",
    "OutlierRule",
    "ExperimentQualityPolicy",
    "CalibrationExperimentReport",
    "CalibrationObservation",
    "SafeBayesianCalibrationOptimizer",
    "CalibrationChange",
    "CalibrationPlan",
    "CalibrationSession",
    "CalibrationExperiment",
    "CalibrationOptimizer",
    "CalibrationMath",
    "SweepParameter",
    "A2LCatalog",
    "A2LObject",
    "A2LAxisDescriptor",
    "A2LCompuMethod",
    "A2LRecordLayout",
    "CalibrationChangeItem",
    "CalibrationChangeSet",
    "CalibrationReview",
    "ChangeSetStatus",
    "ReviewDecision",
    "CalibrationMemoryLayer",
    "CalibrationMemoryLedger",
    "ExperimentEvidence",
    "ExperimentCaseRecord",
    "ExperimentCaseStatus",
    "CalibrationExperimentStore",
    "CalibrationExperimentRunner",
    "ECUCalibrationTask",
    "MultiECUCalibrationCoordinator",
    "CalibrationObjective",
    "CalibrationCandidate",
    "ParetoCalibrationAnalysis",
    "CalibrationTargetAdapter",
    "CANapeCalibrationTarget",
    "InMemoryCalibrationTarget",
    "PersistenceStatus",
    "CalibrationPersistenceJob",
    "CalibrationPersistenceCoordinator",
    "StagedECUPersistenceTask",
    "StagedMultiECUPersistenceCoordinator",
    "AssetManager",
    "AssetRecord",
    "PreflightResult",
    "SignalAnalyzer",
    "Finding",
    "OfflineData",
    "SignalDefinition",
    "SignalDictionary",
    "EngineeringPlatform",
    "Capability",
    "CapabilityRegistry",
    "PermissionLevel",
    "SafetyPolicy",
    "ValueRule",
    "SafeCANape",
    "EnvironmentSecretProvider",
    "WorkflowEngine",
    "WorkflowResult",
    "StepResult",
    "AuditEntry",
    "AuditTrail",
    "Reporter",
    "PluginRegistry",
    "BasicDomainAdapter",
    "built_in_domains",
    "CANapeCOMError",
    "CANapeError",
    "CANapeNotConnectedError",
    "CANapeObjectNotFoundError",
    "CANapeProjectError",
    "OptionalDependencyError",
    "SafetyViolationError",
    "WorkflowError",
    "AssetValidationError",
    "CANapeVersion",
    "CalibrationObjectInfo",
    "DeviceInfo",
    "DiagnosticResponse",
    "FlashStateInfo",
    "RecorderInfo",
    "TaskInfo",
]

__version__ = "3.4.0"
